// Code generated by MCHP Chatbot
/*
 [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include "hal.h"
#include "mcc_generated_files/system/pins.h"
#include "systick/systick.h"
#include "T1S/t1s_lwip.h"
#include "T1S/tc6-lwip.h"
#include "T1S/udp_perf_client.h"
#include "T1S/udp_heartbeat.h"
#include "T1S/eth_heartbeat.h"
#include "app.h"

#include <stdio.h>

/*
    Main application
    
    Role selection:
      - Button NOT pressed at reset -> SERVER (PLCA nodeId=0, IP=192.168.0.100)
        Server blinks LED0 at 500ms and sends heartbeat UDP to client.
      - Button pressed at reset -> CLIENT (PLCA nodeId=1, IP=192.168.0.101)
        Client receives heartbeat and mirrors LED0 state from server.
    
    Switch behavior in normal operation:
      - Short press (SERVER only): toggle iperf UDP throughput test
      - Long press (3s): software reset
*/

/* Network configuration */
#define SERVER_IP_LAST_OCTET    100
#define CLIENT_IP_LAST_OCTET    101
#define SERVER_PLCA_NODE_ID     0
#define CLIENT_PLCA_NODE_ID     1

/* Long press threshold for reset */
#define LONG_PRESS_RESET_MS     3000
/* Delay after button release before executing reset */
#define RESET_DELAY_MS          1000

/* Heartbeat mode switching: alternate between UDP and raw Ethernet */
#define HB_EXCHANGES_PER_MODE   10  /* Switch mode every 10 exchanges */

typedef enum {
    HB_MODE_UDP = 0,        /* Using lwIP UDP heartbeat */
    HB_MODE_RAW_ETH         /* Using raw Ethernet heartbeat (lower RTT) */
} heartbeat_mode_t;

/* Reset state machine */
typedef enum {
    RESET_IDLE = 0,         /* Normal operation */
    RESET_WAITING_RELEASE,  /* Long press detected, LED solid HIGH, waiting for release */
    RESET_COUNTDOWN         /* Button released, counting down to reset */
} reset_state_t;

SYSTICK_TIMEOUT led_toggle;

/* Board role and LED state */
board_role_t board_role;
uint8_t led_state = 0;

/* Reset state */
static reset_state_t reset_state = RESET_IDLE;
static uint32_t reset_release_time = 0;

/* Heartbeat mode switching state (server tracks exchanges, client is reactive) */
static heartbeat_mode_t hb_mode = HB_MODE_UDP;
static uint32_t hb_exchange_count = 0;

int main(void)
{
    HAL_Init();
    
    /* Determine board role from button state at boot.
     * Button pressed (held during reset) = CLIENT
     * Button not pressed = SERVER
     */
    board_role = APP_Button_IsHeldAtBoot() ? BOARD_ROLE_CLIENT : BOARD_ROLE_SERVER;

    SysTick_Initialize();

    /* If button is held (CLIENT role), wait for release before proceeding */
    if (board_role == BOARD_ROLE_CLIENT) {
        while (APP_Button_IsHeldAtBoot()) { }
    }

    APP_Buttons_Init();

    printf("\r\n=== dsPIC33AK512MPS506 Curiosity + T1S ===\r\n");
    if (board_role == BOARD_ROLE_SERVER) {
        printf("Role: SERVER (nodeId=%d, IP=192.168.0.%d)\r\n", SERVER_PLCA_NODE_ID, SERVER_IP_LAST_OCTET);
        printf("  LED blinks at 500ms, heartbeat sent to client\r\n");
    } else {
        printf("Role: CLIENT (nodeId=%d, IP=192.168.0.%d)\r\n", CLIENT_PLCA_NODE_ID, CLIENT_IP_LAST_OCTET);
        printf("  LED mirrors server heartbeat\r\n");
    }
    printf("  Short press: toggle iperf (server only) | Long press (3s): reset\r\n");

    /* Configure T1S network based on role */
    if (board_role == BOARD_ROLE_SERVER) {
        T1S_configure(SERVER_PLCA_NODE_ID, SERVER_IP_LAST_OCTET);
    } else {
        T1S_configure(CLIENT_PLCA_NODE_ID, CLIENT_IP_LAST_OCTET);
    }

    T1S_init();

    /* Point iperf at client board for board-to-board throughput test (server only) */
    if (board_role == BOARD_ROLE_SERVER) {
        iperf_set_remote_ip("192.168.0.101");
    }

    /* Initialize heartbeat modules.
     * UDP heartbeat: Server sends to client IP, client sends ACK back to server IP.
     * Raw ETH heartbeat: Bypasses lwIP entirely for minimum RTT. */
    if (board_role == BOARD_ROLE_SERVER) {
        heartbeat_init(BOARD_ROLE_SERVER, CLIENT_IP_LAST_OCTET);
        eth_heartbeat_init(BOARD_ROLE_SERVER);
    } else {
        heartbeat_init(BOARD_ROLE_CLIENT, SERVER_IP_LAST_OCTET);
        eth_heartbeat_init(BOARD_ROLE_CLIENT);
    }

    /* Register raw Ethernet RX callback for our custom EtherType */
    TC6LwIP_RegisterRawRxCallback(ETH_HB_ETHERTYPE, eth_heartbeat_rx_handler);

    /* Server blinks LED at 500ms; client LED controlled by heartbeat reception */
    if (board_role == BOARD_ROLE_SERVER) {
        SysTick_StartTimeOut(&led_toggle, 500);
    }

    bool iperf_running = false;

    while(1)
    {
        T1S_execute();
        APP_Buttons_Task();

        /* Heartbeat service (handles RX processing and RTT reporting)
         * Disabled during iperf to not interfere with throughput measurement.
         * Both UDP and raw ETH modules are serviced (client is reactive to both). */
        if (!iperf_running) {
            heartbeat_service();
            eth_heartbeat_service();
        }

        /* Short press: toggle iperf (server only) */
        if (APP_Button_WasPressed(APP_BTN_SW1) && board_role == BOARD_ROLE_SERVER)
        {
            if (iperf_running)
            {
                iperf_stop_application();
                heartbeat_set_paused(false);
                eth_heartbeat_set_paused(false);
                printf("iperf stopped - heartbeat resumed\r\n");
                iperf_running = false;
            }
            else
            {
                heartbeat_set_paused(true);
                eth_heartbeat_set_paused(true);
                iperf_start_application();
                printf("iperf started - heartbeat paused\r\n");
                iperf_running = true;
            }
        }

        /* Reset state machine:
         *  1. Long press (3s) -> LED goes solid HIGH, stop blinking
         *  2. Wait for button release
         *  3. After release, wait 1s then execute reset
         *  User can hold button during reset to select CLIENT role. */
        switch (reset_state)
        {
        case RESET_IDLE:
            if (APP_Button_LongPress(LONG_PRESS_RESET_MS))
            {
                reset_state = RESET_WAITING_RELEASE;
                heartbeat_set_paused(true);
                eth_heartbeat_set_paused(true);
                LED0_SetLow();  /* LED ON (active-low) */
                led_state = 1;
                printf("Reset armed - release button to reset\r\n");
            }
            break;

        case RESET_WAITING_RELEASE:
            if (!APP_Button_IsPressed(APP_BTN_SW1))
            {
                /* Button released - start countdown */
                reset_state = RESET_COUNTDOWN;
                reset_release_time = SysTick_GetTickMs();
                printf("Resetting in 1s... (hold button for CLIENT)\r\n");
            }
            break;

        case RESET_COUNTDOWN:
            if ((SysTick_GetTickMs() - reset_release_time) >= RESET_DELAY_MS)
            {
                __asm__ volatile ("reset");
            }
            break;
        }

        /* Server: toggle LED and send heartbeat at 500ms interval.
         * Alternates between UDP and raw Ethernet every HB_EXCHANGES_PER_MODE exchanges.
         * Suspended during iperf and reset sequence.
         * LED is active-low: SetLow = ON, SetHigh = OFF */
        if (board_role == BOARD_ROLE_SERVER && reset_state == RESET_IDLE && !iperf_running)
        {
            if (SysTick_IsTimeoutReached(&led_toggle))
            {
                led_state ^= 1;
                if (led_state) {
                    LED0_SetLow();   /* ON */
                } else {
                    LED0_SetHigh();  /* OFF */
                }

                /* Send via current mode */
                if (hb_mode == HB_MODE_UDP) {
                    heartbeat_send(led_state);
                } else {
                    eth_heartbeat_send(led_state);
                }

                /* Count exchange and switch mode after threshold */
                hb_exchange_count++;
                if (hb_exchange_count >= HB_EXCHANGES_PER_MODE) {
                    hb_exchange_count = 0;
                    /* Reset RTT accumulators to discard transitional measurements */
                    heartbeat_reset_rtt();
                    eth_heartbeat_reset_rtt();
                    if (hb_mode == HB_MODE_UDP) {
                        hb_mode = HB_MODE_RAW_ETH;
                        printf(">> Switching to RAW ETH heartbeat\r\n");
                    } else {
                        hb_mode = HB_MODE_UDP;
                        printf(">> Switching to UDP heartbeat\r\n");
                    }
                }

                SysTick_ResetTimeOut(&led_toggle);
            }
        }
        /* Client: LED is controlled by heartbeat_recv_cb (UDP) or eth_heartbeat_rx_handler (raw ETH).
         * Client is fully reactive - responds in the same protocol it receives.
         * (only while reset_state == RESET_IDLE; during reset sequence LED is solid HIGH) */
    }
}
